# Generated by Django 5.0.7 on 2024-09-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='FacultyPost',
        ),
    ]
